# -*- coding: utf-8 -*-
"""nba-bets-training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19baqLEuHRzPDg_RSgUb-qIWhYl2GLvoS
"""

# Example for compatibility:
# !pip install fsspec==2023.5.0 gcsfs==2023.5.0
!pip install --upgrade fsspec==2023.9.2 gcsfs==2023.9.2

!nvcc --version

!pip uninstall -y bitsandbytes
!pip cache purge  # Clear pip cache
!pip install -U bitsandbytes

# !pip install --no-deps -q datasets requests torch peft bitsandbytes transformers trl accelerate sentencepiece wandb matplotlib
!pip install --no-deps -q datasets requests torch peft transformers trl accelerate sentencepiece wandb matplotlib

import os
from google.colab import userdata
from huggingface_hub import login
import torch
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
)
from datasets import load_dataset
import wandb
from peft import LoraConfig
from trl import SFTTrainer, SFTConfig
from datetime import datetime

os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'

# Commented out IPython magic to ensure Python compatibility.
# Constants

BASE_MODEL = "meta-llama/Meta-Llama-3.1-8B"
PROJECT_NAME = "nba-bets"
HF_USER = "fformenti"

# Data

DATASET_NAME = f"{HF_USER}/nba-bets"
MAX_SEQUENCE_LENGTH = 1024

# Run name for saving the model in the hub

RUN_NAME =  f"{datetime.now():%Y-%m-%d_%H.%M.%S}"
PROJECT_RUN_NAME = f"{PROJECT_NAME}-{RUN_NAME}"
HUB_MODEL_NAME = f"{HF_USER}/{PROJECT_RUN_NAME}"

# Hyperparameters for QLoRA

LORA_R = 32
LORA_ALPHA = 64
TARGET_MODULES = ["q_proj", "v_proj", "k_proj", "o_proj"]
LORA_DROPOUT = 0.1
QUANT_4_BIT = True

# Hyperparameters for Training

EPOCHS = 2
BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 4
LEARNING_RATE = 1e-4
LR_SCHEDULER_TYPE = 'cosine'
WARMUP_RATIO = 0.03
OPTIMIZER = "paged_adamw_32bit"

# Admin config - note that SAVE_STEPS is how often it will upload to the hub
# I've changed this from 5000 to 2000 so that you get more frequent saves

VAL_SIZE = 500
LOG_STEPS = 5
SAVE_STEPS = 100

# STEPS = 50
# SAVE_STEPS = 2000
LOG_TO_WANDB = True

# %matplotlib inline

STEPS = 50
SAVE_STEPS = 2000
LOG_TO_WANDB = True


# Log in to HuggingFace

hf_token = userdata.get('HF_TOKEN')
login(hf_token, add_to_git_credential=True)

# Log in to Weights & Biases
wandb_api_key = userdata.get('WANDB_API_KEY')
os.environ["WANDB_API_KEY"] = wandb_api_key
wandb.login()

# Configure Weights & Biases to record against our project
os.environ["WANDB_PROJECT"] = PROJECT_NAME
os.environ["WANDB_LOG_MODEL"] = "checkpoint" if LOG_TO_WANDB else "end"
os.environ["WANDB_WATCH"] = "gradients"

dataset = load_dataset(DATASET_NAME)
train = dataset['train']
test = dataset['validation']


if LOG_TO_WANDB:
  wandb.init(project=PROJECT_NAME, name=RUN_NAME)

QUANT_4_BIT = False
if QUANT_4_BIT:
  quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_quant_type="nf4"
  )
else:
  quant_config = BitsAndBytesConfig(
    load_in_8bit=True,
    bnb_8bit_compute_dtype=torch.bfloat16
  )



# Load the Tokenizer and the Model

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=quant_config,
    device_map="auto",
)
base_model.generation_config.pad_token_id = tokenizer.pad_token_id

print(f"Memory footprint: {base_model.get_memory_footprint() / 1e6:.1f} MB")


response_template = "The home team finished the game with a point differential of "

lora_parameters = LoraConfig(
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    r=LORA_R,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=TARGET_MODULES,
)

train_parameters = SFTConfig(
    output_dir=PROJECT_RUN_NAME,
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=1,
    eval_strategy="no",
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    optim=OPTIMIZER,
    save_steps=SAVE_STEPS,
    save_total_limit=10,
    logging_steps=STEPS,
    learning_rate=LEARNING_RATE,
    weight_decay=0.001,
    fp16=False,
    bf16=True,
    max_grad_norm=0.3,
    max_steps=-1,
    warmup_ratio=WARMUP_RATIO,
    # group_by_length=True,
    lr_scheduler_type=LR_SCHEDULER_TYPE,
    report_to="wandb" if LOG_TO_WANDB else None,
    run_name=RUN_NAME,
    # max_seq_length=MAX_SEQUENCE_LENGTH,
    dataset_text_field="text",
    save_strategy="steps",
    hub_strategy="every_save",
    push_to_hub=True,
    hub_model_id=HUB_MODEL_NAME,
    hub_private_repo=True,
    # eval_steps=SAVE_STEPS, #added
)

fine_tuning = SFTTrainer(
    model=base_model,
    train_dataset=train,
    # eval_dataset=val, # added
    peft_config=lora_parameters,
    args=train_parameters,
    # data_collator=collator
  )

print(tokenizer.tokenize(response_template))

print(tokenizer.tokenize(train[0]["text"]))

fine_tuning.train()

PROJECT_RUN_NAME

# Push our fine-tuned model to Hugging Face
fine_tuning.model.push_to_hub(PROJECT_RUN_NAME, private=True)
print(f"Saved to the hub: {PROJECT_RUN_NAME}")

if LOG_TO_WANDB:
  wandb.finish()

!wget -q https://raw.githubusercontent.com/ed-donner/llm_engineering/main/week7/util.py -O util.py

from peft import PeftModel
# from util import evaluate

from transformers import set_seed

fine_tuned_model = PeftModel.from_pretrained(base_model, HUB_MODEL_NAME)

def model_predict(item):
    inputs = tokenizer(item["text"],return_tensors="pt").to("cuda")
    with torch.no_grad():
        output_ids = fine_tuned_model.generate(**inputs, max_new_tokens=8)
    prompt_len = inputs["input_ids"].shape[1]
    generated_ids = output_ids[0, prompt_len:]
    return tokenizer.decode(generated_ids)

test[0]

import math
import re
from itertools import accumulate

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from IPython.display import clear_output
from sklearn.metrics import mean_squared_error, r2_score
from tqdm.auto import tqdm

GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
RESET = "\033[0m"
COLOR_MAP = {"red": RED, "orange": YELLOW, "green": GREEN}

DEFAULT_SIZE = 200


class Tester:
    def __init__(self, predictor, data, title=None, size=DEFAULT_SIZE):
        self.predictor = predictor
        self.data = data
        self.title = title or self.make_title(predictor)
        self.size = size
        self.titles = []
        self.guesses = []
        self.truths = []
        self.errors = []
        self.colors = []

    @staticmethod
    def make_title(predictor) -> str:
        return (
            predictor.__name__.replace("__", ".")
            .replace("_", " ")
            .title()
            .replace("Gpt", "GPT")
        )

    @staticmethod
    def post_process(value):
        if isinstance(value, str):
            value = value.replace("$", "").replace(",", "")
            match = re.search(r"[-+]?\d*\.\d+|\d+", value)
            return float(match.group()) if match else 0
        else:
            return value

    def color_for(self, error, truth):
        if error < 5:
            return "green"
        elif error < 10:
            return "orange"
        else:
            return "red"

    def run_datapoint(self, i):
        datapoint = self.data[i]
        value = self.predictor(datapoint)
        guess = self.post_process(value)
        truth = float(datapoint["point_diff"])
        error = abs(guess - truth)
        color = self.color_for(error, truth)
        pieces = datapoint["text"].split("Title: ")
        title = pieces[1].split("\n")[0] if len(pieces) > 1 else pieces[0]
        title = title if len(title) <= 40 else title[:40] + "..."
        return title, guess, truth, error, color

    def chart(self, title):
        df = pd.DataFrame(
            {
                "truth": self.truths,
                "guess": self.guesses,
                "title": self.titles,
                "error": self.errors,
                "color": self.colors,
            }
        )

        # Pre-format hover text
        df["hover"] = [
            f"{t}\nGuess=${g:,.2f} Actual=${y:,.2f}"
            for t, g, y in zip(df["title"], df["guess"], df["truth"])
        ]

        max_val = float(max(df["truth"].max(), df["guess"].max()))

        fig = px.scatter(
            df,
            x="truth",
            y="guess",
            color="color",
            color_discrete_map={"green": "green", "orange": "orange", "red": "red"},
            title=title,
            labels={"truth": "Actual Price", "guess": "Predicted Price"},
            width=800,
            height=600,
        )

        # Assign customdata per trace (one color/category = one trace)
        for tr in fig.data:
            mask = df["color"] == tr.name
            tr.customdata = df.loc[mask, ["hover"]].to_numpy()
            tr.hovertemplate = "%{customdata[0]}<extra></extra>"
            tr.marker.update(size=6)

        # Reference line y=x
        fig.add_trace(
            go.Scatter(
                x=[0, max_val],
                y=[0, max_val],
                mode="lines",
                line=dict(width=2, dash="dash", color="deepskyblue"),
                name="y = x",
                hoverinfo="skip",
                showlegend=False,
            )
        )

        fig.update_xaxes(range=[0, max_val])
        fig.update_yaxes(range=[0, max_val])
        fig.update_layout(showlegend=False)
        fig.show()

    def error_trend_chart(self):
        n = len(self.errors)

        # Running mean and std (pure Python)
        running_sums = list(accumulate(self.errors))
        x = list(range(1, n + 1))
        running_means = [s / i for s, i in zip(running_sums, x)]

        running_squares = list(accumulate(e * e for e in self.errors))
        running_stds = [
            math.sqrt((sq_sum / i) - (mean**2)) if i > 1 else 0
            for i, sq_sum, mean in zip(x, running_squares, running_means)
        ]

        # 95% confidence interval for mean
        ci = [
            1.96 * (sd / math.sqrt(i)) if i > 1 else 0 for i, sd in zip(x, running_stds)
        ]
        upper = [m + c for m, c in zip(running_means, ci)]
        lower = [m - c for m, c in zip(running_means, ci)]

        # Title with final stats
        final_mean = running_means[-1]
        final_ci = ci[-1]
        title = f"{self.title} Error: {final_mean:,.2f} ± {final_ci:,.2f}"

        # Plot
        fig = go.Figure()

        # Shaded confidence interval band
        fig.add_trace(
            go.Scatter(
                x=x + x[::-1],
                y=upper + lower[::-1],
                fill="toself",
                fillcolor="rgba(128,128,128,0.2)",
                line=dict(color="rgba(255,255,255,0)"),
                hoverinfo="skip",
                showlegend=False,
                name="95% CI",
            )
        )

        # Main line with hover text showing CI
        fig.add_trace(
            go.Scatter(
                x=x,
                y=running_means,
                mode="lines",
                line=dict(width=3, color="firebrick"),
                name="Cumulative Avg Error",
                customdata=list(
                    zip(
                        ci,
                    )
                ),
                hovertemplate=(
                    "n=%{x}<br>"
                    "Avg Error=$%{y:,.2f}<br>"
                    "±95% CI=$%{customdata[0]:,.2f}<extra></extra>"
                ),
            )
        )

        fig.update_layout(
            title=title,
            xaxis_title="Number of Datapoints",
            yaxis_title="Error ($)",
            width=800,
            height=300,
            template="plotly_white",
            showlegend=False,
        )

        fig.show()

    def report(self):
        average_error = sum(self.errors) / self.size
        mse = mean_squared_error(self.truths, self.guesses)
        r2 = r2_score(self.truths, self.guesses) * 100
        title = f"{self.title} results<br><b>Error:</b> ${average_error:,.2f} <b>MSE:</b> {mse:,.0f} <b>r²:</b> {r2:.1f}%"
        self.error_trend_chart()
        self.chart(title)

    def run(self):
        for i in tqdm(range(self.size)):
            title, guess, truth, error, color = self.run_datapoint(i)
            self.titles.append(title)
            self.guesses.append(guess)
            self.truths.append(truth)
            self.errors.append(error)
            self.colors.append(color)
            print(f"{COLOR_MAP[color]}${error:.0f} ", end="")
        clear_output(wait=True)
        self.report()


def evaluate(function, data, size=DEFAULT_SIZE):
    Tester(function, data, size=size).run()

set_seed(42)
evaluate(model_predict, test)

import math
import re
from itertools import accumulate

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from IPython.display import clear_output
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score
from tqdm.auto import tqdm

GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
RESET = "\033[0m"
COLOR_MAP = {"red": RED, "orange": YELLOW, "green": GREEN}

DEFAULT_SIZE = 200


class Tester_Regressors:
    def __init__(self, predictor, data, title=None, size=DEFAULT_SIZE):
        self.predictor = predictor
        self.data = data
        self.title = title or self.make_title(predictor)
        self.size = size
        self.titles = []
        self.guesses = []
        self.truths = []
        self.errors = []
        self.colors = []

    @staticmethod
    def make_title(predictor) -> str:
        return (
            predictor.__name__.replace("__", ".")
            .replace("_", " ")
            .title()
            .replace("Gpt", "GPT")
        )

    @staticmethod
    def post_process(value):
        if isinstance(value, str):
            value = value.replace("$", "").replace(",", "")
            match = re.search(r"[-+]?\d*\.\d+|\d+", value)
            return float(match.group()) if match else 0
        else:
            return value

    def color_for(self, error, truth):
        if error < 40 or error / truth < 0.2:
            return "green"
        elif error < 80 or error / truth < 0.4:
            return "orange"
        else:
            return "red"

    def run_datapoint(self, i):
        datapoint = self.data[i]
        value = self.predictor(datapoint)
        guess = self.post_process(value)
        truth = float(datapoint["point_diff"])
        error = abs(guess - truth)
        color = self.color_for(error, truth)
        pieces = datapoint["text"].split("Title: ")
        title = pieces[1].split("\n")[0] if len(pieces) > 1 else pieces[0]
        title = title if len(title) <= 40 else title[:40] + "..."
        return title, guess, truth, error, color

    def chart(self, title):
        df = pd.DataFrame(
            {
                "truth": self.truths,
                "guess": self.guesses,
                "title": self.titles,
                "error": self.errors,
                "color": self.colors,
            }
        )

        # Pre-format hover text
        df["hover"] = [
            f"{t}\nGuess=${g:,.2f} Actual=${y:,.2f}"
            for t, g, y in zip(df["title"], df["guess"], df["truth"])
        ]

        # Allow both axes to show negative values (the previous implementation
        # hard-clamped ranges to start at 0).
        min_val = float(min(df["truth"].min(), df["guess"].min()))
        max_val = float(max(df["truth"].max(), df["guess"].max()))
        if min_val == max_val:
            # Avoid Plotly throwing on a zero-span range.
            min_val -= 1
            max_val += 1

        fig = px.scatter(
            df,
            x="truth",
            y="guess",
            color="color",
            color_discrete_map={"green": "green", "orange": "orange", "red": "red"},
            title=title,
            labels={"truth": "Actual Price", "guess": "Predicted Price"},
            width=800,
            height=600,
        )

        # Assign customdata per trace (one color/category = one trace)
        for tr in fig.data:
            mask = df["color"] == tr.name
            tr.customdata = df.loc[mask, ["hover"]].to_numpy()
            tr.hovertemplate = "%{customdata[0]}<extra></extra>"
            tr.marker.update(size=6)

        # Reference line y=x
        fig.add_trace(
            go.Scatter(
                x=[min_val, max_val],
                y=[min_val, max_val],
                mode="lines",
                line=dict(width=2, dash="dash", color="deepskyblue"),
                name="y = x",
                hoverinfo="skip",
                showlegend=False,
            )
        )

        fig.update_xaxes(range=[min_val, max_val])
        fig.update_yaxes(range=[min_val, max_val])
        fig.update_layout(showlegend=False)
        fig.show()

    def error_trend_chart(self):
        n = len(self.errors)

        # Running mean and std (pure Python)
        running_sums = list(accumulate(self.errors))
        x = list(range(1, n + 1))
        running_means = [s / i for s, i in zip(running_sums, x)]

        running_squares = list(accumulate(e * e for e in self.errors))
        running_stds = [
            math.sqrt((sq_sum / i) - (mean**2)) if i > 1 else 0
            for i, sq_sum, mean in zip(x, running_squares, running_means)
        ]

        # 95% confidence interval for mean
        ci = [
            1.96 * (sd / math.sqrt(i)) if i > 1 else 0 for i, sd in zip(x, running_stds)
        ]
        upper = [m + c for m, c in zip(running_means, ci)]
        lower = [m - c for m, c in zip(running_means, ci)]

        # Title with final stats
        final_mean = running_means[-1]
        final_ci = ci[-1]
        title = f"{self.title} Error: {final_mean:,.2f} ± {final_ci:,.2f}"

        # Plot
        fig = go.Figure()

        # Shaded confidence interval band
        fig.add_trace(
            go.Scatter(
                x=x + x[::-1],
                y=upper + lower[::-1],
                fill="toself",
                fillcolor="rgba(128,128,128,0.2)",
                line=dict(color="rgba(255,255,255,0)"),
                hoverinfo="skip",
                showlegend=False,
                name="95% CI",
            )
        )

        # Main line with hover text showing CI
        fig.add_trace(
            go.Scatter(
                x=x,
                y=running_means,
                mode="lines",
                line=dict(width=3, color="firebrick"),
                name="Cumulative Avg Error",
                customdata=list(
                    zip(
                        ci,
                    )
                ),
                hovertemplate=(
                    "n=%{x}<br>"
                    "Avg Error=$%{y:,.2f}<br>"
                    "±95% CI=$%{customdata[0]:,.2f}<extra></extra>"
                ),
            )
        )

        fig.update_layout(
            title=title,
            xaxis_title="Number of Datapoints",
            yaxis_title="Error ($)",
            width=800,
            height=300,
            template="plotly_white",
            showlegend=False,
        )

        fig.show()

    def report(self):
        average_error = sum(self.errors) / self.size
        mse = mean_squared_error(self.truths, self.guesses)
        r2 = r2_score(self.truths, self.guesses) * 100
        title = f"{self.title} results<br><b>Error:</b> ${average_error:,.2f} <b>MSE:</b> {mse:,.0f} <b>r²:</b> {r2:.1f}%"
        self.error_trend_chart()
        self.chart(title)

    def run(self):
        for i in tqdm(range(self.size)):
            title, guess, truth, error, color = self.run_datapoint(i)
            self.titles.append(title)
            self.guesses.append(guess)
            self.truths.append(truth)
            self.errors.append(error)
            self.colors.append(color)
            print(f"{COLOR_MAP[color]}${error:.0f} ", end="")
        clear_output(wait=True)
        self.report()


class Tester_Classifiers:
    """Evaluate a predictor as a binary classifier via sign agreement.

    A prediction is correct (1) when guess and truth share a sign
    (both > 0 or both <= 0), and incorrect (0) otherwise.
    """

    def __init__(self, predictor, data, title=None, size=DEFAULT_SIZE):
        self.predictor = predictor
        self.data = data
        self.title = title or Tester_Regressors.make_title(predictor)
        self.size = size
        self.titles = []
        self.guesses = []
        self.truths = []
        self.corrects = []
        self.colors = []

    @staticmethod
    def post_process(value):
        return Tester_Regressors.post_process(value)

    @staticmethod
    def is_correct(guess, truth) -> int:
        """1 if same sign (both positive or both non-positive), else 0."""
        return int((guess > 0) == (truth > 0))

    def color_for(self, correct: int) -> str:
        return "green" if correct else "red"

    def run_datapoint(self, i):
        datapoint = self.data[i]
        value = self.predictor(datapoint)
        guess = self.post_process(value)
        truth = float(datapoint["point_diff"])
        correct = self.is_correct(guess, truth)
        color = self.color_for(correct)
        pieces = datapoint["text"].split("Title: ")
        title = pieces[1].split("\n")[0] if len(pieces) > 1 else pieces[0]
        title = title if len(title) <= 40 else title[:40] + "..."
        return title, guess, truth, correct, color

    def chart(self, title):
        df = pd.DataFrame(
            {
                "truth": self.truths,
                "guess": self.guesses,
                "title": self.titles,
                "correct": self.corrects,
                "color": self.colors,
            }
        )

        df["hover"] = [
            f"{t}\nGuess={g:+.0f} Actual={y:+.0f}\n{'Correct' if c else 'Wrong'}"
            for t, g, y, c in zip(
                df["title"], df["guess"], df["truth"], df["correct"]
            )
        ]

        min_val = float(min(df["truth"].min(), df["guess"].min()))
        max_val = float(max(df["truth"].max(), df["guess"].max()))
        if min_val == max_val:
            min_val -= 1
            max_val += 1

        fig = px.scatter(
            df,
            x="truth",
            y="guess",
            color="color",
            color_discrete_map={"green": "green", "red": "red"},
            title=title,
            labels={"truth": "Actual Diff", "guess": "Predicted Diff"},
            width=800,
            height=600,
        )

        for tr in fig.data:
            mask = df["color"] == tr.name
            tr.customdata = df.loc[mask, ["hover"]].to_numpy()
            tr.hovertemplate = "%{customdata[0]}<extra></extra>"
            tr.marker.update(size=6)

        # Quadrant guides at zero (sign boundary)
        fig.add_hline(y=0, line_width=1, line_dash="dot", line_color="gray")
        fig.add_vline(x=0, line_width=1, line_dash="dot", line_color="gray")

        fig.update_xaxes(range=[min_val, max_val])
        fig.update_yaxes(range=[min_val, max_val])
        fig.update_layout(showlegend=False)
        fig.show()

    def accuracy_trend_chart(self):
        n = len(self.corrects)
        running_sums = list(accumulate(self.corrects))
        x = list(range(1, n + 1))
        running_acc = [s / i for s, i in zip(running_sums, x)]

        final_acc = running_acc[-1]
        title = f"{self.title} Accuracy: {final_acc:.1%}"

        fig = go.Figure()
class Tester_Classifiers:
    """Evaluate a predictor as a binary classifier via sign agreement.

    A prediction is correct (1) when guess and truth share a sign
    (both > 0 or both <= 0), and incorrect (0) otherwise.
    """

    def __init__(self, predictor, data, title=None, size=DEFAULT_SIZE):
        self.predictor = predictor
        self.data = data
        self.title = title or Tester_Regressors.make_title(predictor)
        self.size = size
        self.titles = []
        self.guesses = []
        self.truths = []
        self.corrects = []
        self.colors = []

    @staticmethod
    def post_process(value):
        return Tester_Regressors.post_process(value)

    @staticmethod
    def is_correct(guess, truth) -> int:
        """1 if same sign (both positive or both non-positive), else 0."""
        return int((guess > 0) == (truth > 0))

    def color_for(self, correct: int) -> str:
        return "green" if correct else "red"

    def run_datapoint(self, i):
        datapoint = self.data[i]
        value = self.predictor(datapoint)
        guess = self.post_process(value)
        truth = float(datapoint["point_diff"])
        correct = self.is_correct(guess, truth)
        color = self.color_for(correct)
        pieces = datapoint["text"].split("Title: ")
        title = pieces[1].split("\n")[0] if len(pieces) > 1 else pieces[0]
        title = title if len(title) <= 40 else title[:40] + "..."
        return title, guess, truth, correct, color

    def chart(self, title):
        df = pd.DataFrame(
            {
                "truth": self.truths,
                "guess": self.guesses,
                "title": self.titles,
                "correct": self.corrects,
                "color": self.colors,
            }
        )

        df["hover"] = [
            f"{t}\nGuess={g:+.0f} Actual={y:+.0f}\n{'Correct' if c else 'Wrong'}"
            for t, g, y, c in zip(
                df["title"], df["guess"], df["truth"], df["correct"]
            )
        ]

        min_val = float(min(df["truth"].min(), df["guess"].min()))
        max_val = float(max(df["truth"].max(), df["guess"].max()))
        if min_val == max_val:
            min_val -= 1
            max_val += 1

        fig = px.scatter(
            df,
            x="truth",
            y="guess",
            color="color",
            color_discrete_map={"green": "green", "red": "red"},
            title=title,
            labels={"truth": "Actual Diff", "guess": "Predicted Diff"},
            width=800,
            height=600,
        )

        for tr in fig.data:
            mask = df["color"] == tr.name
            tr.customdata = df.loc[mask, ["hover"]].to_numpy()
            tr.hovertemplate = "%{customdata[0]}<extra></extra>"
            tr.marker.update(size=6)

        # Quadrant guides at zero (sign boundary)
        fig.add_hline(y=0, line_width=1, line_dash="dot", line_color="gray")
        fig.add_vline(x=0, line_width=1, line_dash="dot", line_color="gray")

        fig.update_xaxes(range=[min_val, max_val])
        fig.update_yaxes(range=[min_val, max_val])
        fig.update_layout(showlegend=False)
        fig.show()

    def accuracy_trend_chart(self):
        n = len(self.corrects)
        running_sums = list(accumulate(self.corrects))
        x = list(range(1, n + 1))
        running_acc = [s / i for s, i in zip(running_sums, x)]

        final_acc = running_acc[-1]
        title = f"{self.title} Accuracy: {final_acc:.1%}"

        fig = go.Figure()
        fig.add_trace(
            go.Scatter(
                x=x,
                y=running_acc,
                mode="lines",
                line=dict(width=3, color="firebrick"),
                name="Cumulative Accuracy",
                hovertemplate="n=%{x}<br>Accuracy=%{y:.1%}<extra></extra>",
            )
        )
        fig.add_hline(
            y=0.5,
            line_width=1,
            line_dash="dash",
            line_color="gray",
            annotation_text="chance (50%)",
        )

        fig.update_layout(
            title=title,
            xaxis_title="Number of Datapoints",
            yaxis_title="Accuracy",
            yaxis=dict(tickformat=".0%", range=[0, 1]),
            width=800,
            height=300,
            template="plotly_white",
            showlegend=False,
        )
        fig.show()

    def confidence_accuracy_chart(self):
        """Accuracy among top-k predictions by |predicted point_diff| (desc).

        Games with a larger predicted margin are treated as higher confidence;
        the curve shows whether those are easier to get right.
        """
        n = len(self.corrects)
        ranked = sorted(
            zip(self.guesses, self.corrects),
            key=lambda pair: abs(pair[0]),
            reverse=True,
        )
        margins = [abs(g) for g, _ in ranked]
        corrects_ranked = [c for _, c in ranked]

        running_sums = list(accumulate(corrects_ranked))
        x = [i / n for i in range(1, n + 1)]
        running_acc = [s / i for s, i in zip(running_sums, range(1, n + 1))]
        overall_acc = running_sums[-1] / n

        fig = go.Figure()
        fig.add_trace(
            go.Scatter(
                x=x,
                y=running_acc,
                mode="lines",
                line=dict(width=3, color="steelblue"),
                name="Accuracy @ coverage",
                customdata=list(zip(range(1, n + 1), margins)),
                hovertemplate=(
                    "Coverage=%{x:.1%}<br>"
                    "Top-n=%{customdata[0]}<br>"
                    "|pred|=%{customdata[1]:.1f}<br>"
                    "Accuracy=%{y:.1%}<extra></extra>"
                ),
            )
        )
        fig.add_hline(
            y=overall_acc,
            line_width=1,
            line_dash="dash",
            line_color="gray",
            annotation_text=f"overall ({overall_acc:.1%})",
        )
        fig.add_hline(
            y=0.5,
            line_width=1,
            line_dash="dot",
            line_color="lightgray",
            annotation_text="chance (50%)",
        )

        fig.update_layout(
            title=(
                f"{self.title} Confidence Curve<br>"
                f"<sup>Sorted by |predicted point_diff| descending</sup>"
            ),
            xaxis_title="Coverage (fraction of games, high |pred| first)",
            yaxis_title="Cumulative Accuracy",
            xaxis=dict(tickformat=".0%", range=[0, 1]),
            yaxis=dict(tickformat=".0%", range=[0, 1]),
            width=800,
            height=400,
            template="plotly_white",
            showlegend=False,
        )
        fig.show()

    def report(self):
        # Labels from sign: positive → 1, non-positive → 0
        y_true = [int(t > 0) for t in self.truths]
        y_pred = [int(g > 0) for g in self.guesses]
        acc = accuracy_score(y_true, y_pred)
        n_correct = sum(self.corrects)
        title = (
            f"{self.title} results<br>"
            f"<b>Accuracy:</b> {acc:.1%} "
            f"({n_correct}/{self.size})"
        )
        self.accuracy_trend_chart()
        self.confidence_accuracy_chart()
        self.chart(title)

    def run(self):
        for i in tqdm(range(self.size)):
            title, guess, truth, correct, color = self.run_datapoint(i)
            self.titles.append(title)
            self.guesses.append(guess)
            self.truths.append(truth)
            self.corrects.append(correct)
            self.colors.append(color)
            mark = "✓" if correct else "✗"
            print(f"{COLOR_MAP[color]}{mark} ", end="")
        clear_output(wait=True)
        self.report()


def evaluate(function, data, size=DEFAULT_SIZE):
    Tester_Regressors(function, data, size=size).run()


def evaluate_classifier(function, data, size=DEFAULT_SIZE):
    Tester_Classifiers(function, data, size=size).run()

set_seed(42)
evaluate_classifier(model_predict, test)
