"""
Configuration module for NBA betting project.

This module contains:
- Path constants for data files
- AWS configuration
- Project-level settings
"""

from .paths import (
    PROJECT_ROOT,
    RAW_GAMES_PATH,
    TEAMS_CITIES_CONFERENCE_HISTORY_HANDMADE_PATH,
    RAW_INCREMENTAL_DIR,
    RAW_INCREMENTAL_ARCHIVE_DIR,
    LEAGUE_SCHEDULE_PATH,
    INGESTED_GAMES_PATH,
    # INGESTED_INCREMENTAL_GAMES_PATH,
    REGULAR_SEASON_GAMES_PATH,
    NON_POSITIVE_SCORE_PATH,
    PLAYOFFS_GAMES_PATH,
    TEAMS_CITIES_CONFERENCE_HISTORY_PROCESSED_PATH,
    TEAMS_HOME_RECORDS_PATH,
    TEAMS_AWAY_RECORDS_PATH,
    TEAMS_RECORDS_PATH,
    TEAMS_HOME_PTS_DIFF_PATH,
    TEAMS_AWAY_PTS_DIFF_PATH,
    TEAMS_PTS_DIFF_PATH,
    EAST_WEST_RECORDS_PATH,
    EAST_WEST_RECORDS_AT_EAST_PATH,
    EAST_WEST_RECORDS_AT_WEST_PATH,
    RESTED_DAYS_PATH,
    GAMES_FEATURES_PATH,
)
from .aws import AWS_BUCKET_NAME, AWS_PROCESSED_FOLDER
from .constants import EARLIEST_GAME_DATE, CURRENT_SEASON_START_YEAR

__all__ = [
    "PROJECT_ROOT",
    "RAW_GAMES_PATH",
    "TEAMS_CITIES_CONFERENCE_HISTORY_HANDMADE_PATH",
    "RAW_INCREMENTAL_DIR",
    "RAW_INCREMENTAL_ARCHIVE_DIR",
    "LEAGUE_SCHEDULE_PATH",
    "INGESTED_GAMES_PATH",
    # "INGESTED_INCREMENTAL_GAMES_PATH",
    "REGULAR_SEASON_GAMES_PATH",
    "NON_POSITIVE_SCORE_PATH",
    "PLAYOFFS_GAMES_PATH",
    "TEAMS_CITIES_CONFERENCE_HISTORY_PROCESSED_PATH",
    "TEAMS_HOME_RECORDS_PATH",
    "TEAMS_AWAY_RECORDS_PATH",
    "TEAMS_RECORDS_PATH",
    "TEAMS_HOME_PTS_DIFF_PATH",
    "TEAMS_AWAY_PTS_DIFF_PATH",
    "TEAMS_PTS_DIFF_PATH",
    "EAST_WEST_RECORDS_PATH",
    "EAST_WEST_RECORDS_AT_EAST_PATH",
    "EAST_WEST_RECORDS_AT_WEST_PATH",
    "RESTED_DAYS_PATH",
    "GAMES_FEATURES_PATH",
    "AWS_BUCKET_NAME",
    "AWS_PROCESSED_FOLDER",
    "EARLIEST_GAME_DATE",
    "CURRENT_SEASON_START_YEAR",
]

# Backward compatibility - import from config instead of constants
from .paths import *  # noqa: F403, F405
from .aws import *  # noqa: F403, F405
from .constants import *  # noqa: F403, F405
